### ISSUE TITLE
Update Cargo.toml for bdf-parser

### ISSUE THREAD

**Issue by rfuest** [embedded-graphics/bdf#19]
The `Cargo.toml` file contains references to `.travis.yml`, a travis-ci badge and old repository and doc links.

**Comment by jamwaffles** [comment]
I just did a search for `travis` and a quick audit of all github.com links in the repo and couldn't find mention of Travis or old repo links, so I think this issue can be closed now?

**Comment by rfuest** [comment]
Yes, it can be closed.
